export const LOG_IN_ACTION = "LOG_IN_ACTION";
export const LOG_OUT_ACTION = "LOG_OUT_ACTION";
export const USER_INFO_REFRESH = "USER_INFO_REFRESH";
export const GET_POST_DATA = "GET_POST_DATA";
export const REMOVE_POST_ACTION = "REMOVE_POST_ACTION";
export const UPDATE_POST_ACTION = "UPDATE_POST_ACTION";
export const ADD_COMMENT_ACTION = "ADD_COMMENT_ACTION";
